// <auto-generated />
using System;
using Lesson.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lesson.Migrations
{
    [DbContext(typeof(MobileContext))]
    [Migration("20230928113131_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lesson.Models.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Link = "https://apple.com",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2L,
                            Link = "https://apple.com",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3L,
                            Link = "https://apple.com",
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = 4L,
                            Link = "https://huawei.com",
                            Name = "Huawei"
                        });
                });

            modelBuilder.Entity("Lesson.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("PhoneId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PhoneId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Lesson.Models.Phone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short?>("BatteryCapacity")
                        .HasColumnType("smallint");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayType")
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<short?>("Ram")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BatteryCapacity = (short)3483,
                            BrandId = 3L,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            DisplayType = "Steel",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2370m,
                            Title = "Small Granite Sausages"
                        },
                        new
                        {
                            Id = 2L,
                            BatteryCapacity = (short)4003,
                            BrandId = 4L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Metal",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3502m,
                            Title = "Sleek Metal Keyboard"
                        },
                        new
                        {
                            Id = 3L,
                            BatteryCapacity = (short)3349,
                            BrandId = 2L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Cotton",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2346m,
                            Title = "Intelligent Granite Bacon"
                        },
                        new
                        {
                            Id = 4L,
                            BatteryCapacity = (short)3088,
                            BrandId = 3L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Wooden",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4116m,
                            Title = "Handcrafted Rubber Salad"
                        },
                        new
                        {
                            Id = 5L,
                            BatteryCapacity = (short)3615,
                            BrandId = 3L,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2738m,
                            Title = "Fantastic Steel Mouse"
                        },
                        new
                        {
                            Id = 6L,
                            BatteryCapacity = (short)3919,
                            BrandId = 2L,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            DisplayType = "Plastic",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1118m,
                            Title = "Generic Soft Chips"
                        },
                        new
                        {
                            Id = 7L,
                            BatteryCapacity = (short)5202,
                            BrandId = 2L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Frozen",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3243m,
                            Title = "Incredible Granite Keyboard"
                        },
                        new
                        {
                            Id = 8L,
                            BatteryCapacity = (short)3353,
                            BrandId = 3L,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            DisplayType = "Plastic",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3966m,
                            Title = "Fantastic Concrete Shoes"
                        },
                        new
                        {
                            Id = 9L,
                            BatteryCapacity = (short)4752,
                            BrandId = 2L,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            DisplayType = "Wooden",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1023m,
                            Title = "Refined Granite Car"
                        },
                        new
                        {
                            Id = 10L,
                            BatteryCapacity = (short)5114,
                            BrandId = 3L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Frozen",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2079m,
                            Title = "Fantastic Cotton Chips"
                        },
                        new
                        {
                            Id = 11L,
                            BatteryCapacity = (short)5139,
                            BrandId = 3L,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            DisplayType = "Fresh",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4347m,
                            Title = "Awesome Soft Pizza"
                        },
                        new
                        {
                            Id = 12L,
                            BatteryCapacity = (short)3779,
                            BrandId = 2L,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4157m,
                            Title = "Licensed Concrete Soap"
                        },
                        new
                        {
                            Id = 13L,
                            BatteryCapacity = (short)4415,
                            BrandId = 3L,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            DisplayType = "Rubber",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2828m,
                            Title = "Sleek Granite Towels"
                        },
                        new
                        {
                            Id = 14L,
                            BatteryCapacity = (short)4158,
                            BrandId = 4L,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            DisplayType = "Metal",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3564m,
                            Title = "Handcrafted Rubber Chips"
                        },
                        new
                        {
                            Id = 15L,
                            BatteryCapacity = (short)4967,
                            BrandId = 3L,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            DisplayType = "Frozen",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2696m,
                            Title = "Generic Frozen Pizza"
                        },
                        new
                        {
                            Id = 16L,
                            BatteryCapacity = (short)4235,
                            BrandId = 1L,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            DisplayType = "Cotton",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3152m,
                            Title = "Unbranded Rubber Hat"
                        },
                        new
                        {
                            Id = 17L,
                            BatteryCapacity = (short)3158,
                            BrandId = 2L,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            DisplayType = "Concrete",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2196m,
                            Title = "Tasty Frozen Pizza"
                        },
                        new
                        {
                            Id = 18L,
                            BatteryCapacity = (short)4323,
                            BrandId = 4L,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            DisplayType = "Plastic",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3773m,
                            Title = "Practical Metal Keyboard"
                        },
                        new
                        {
                            Id = 19L,
                            BatteryCapacity = (short)4697,
                            BrandId = 3L,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            DisplayType = "Frozen",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3918m,
                            Title = "Awesome Wooden Sausages"
                        },
                        new
                        {
                            Id = 20L,
                            BatteryCapacity = (short)5893,
                            BrandId = 3L,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            DisplayType = "Fresh",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1911m,
                            Title = "Licensed Wooden Chips"
                        },
                        new
                        {
                            Id = 21L,
                            BatteryCapacity = (short)4501,
                            BrandId = 2L,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            DisplayType = "Wooden",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1149m,
                            Title = "Refined Granite Cheese"
                        },
                        new
                        {
                            Id = 22L,
                            BatteryCapacity = (short)3589,
                            BrandId = 4L,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            DisplayType = "Steel",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4126m,
                            Title = "Small Cotton Bacon"
                        },
                        new
                        {
                            Id = 23L,
                            BatteryCapacity = (short)5232,
                            BrandId = 3L,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            DisplayType = "Concrete",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4322m,
                            Title = "Intelligent Rubber Chair"
                        },
                        new
                        {
                            Id = 24L,
                            BatteryCapacity = (short)3952,
                            BrandId = 3L,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            DisplayType = "Steel",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1829m,
                            Title = "Awesome Wooden Shirt"
                        },
                        new
                        {
                            Id = 25L,
                            BatteryCapacity = (short)4101,
                            BrandId = 1L,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            DisplayType = "Fresh",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4335m,
                            Title = "Practical Soft Pants"
                        },
                        new
                        {
                            Id = 26L,
                            BatteryCapacity = (short)4201,
                            BrandId = 4L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Cotton",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1187m,
                            Title = "Tasty Frozen Bike"
                        },
                        new
                        {
                            Id = 27L,
                            BatteryCapacity = (short)4158,
                            BrandId = 2L,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            DisplayType = "Rubber",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4497m,
                            Title = "Refined Concrete Computer"
                        },
                        new
                        {
                            Id = 28L,
                            BatteryCapacity = (short)3151,
                            BrandId = 1L,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            DisplayType = "Rubber",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3136m,
                            Title = "Incredible Plastic Hat"
                        },
                        new
                        {
                            Id = 29L,
                            BatteryCapacity = (short)5935,
                            BrandId = 2L,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            DisplayType = "Concrete",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3332m,
                            Title = "Intelligent Soft Bike"
                        },
                        new
                        {
                            Id = 30L,
                            BatteryCapacity = (short)4906,
                            BrandId = 3L,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            DisplayType = "Steel",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4479m,
                            Title = "Awesome Cotton Bike"
                        },
                        new
                        {
                            Id = 31L,
                            BatteryCapacity = (short)5095,
                            BrandId = 4L,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2272m,
                            Title = "Licensed Metal Soap"
                        },
                        new
                        {
                            Id = 32L,
                            BatteryCapacity = (short)3741,
                            BrandId = 1L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1988m,
                            Title = "Rustic Cotton Pizza"
                        },
                        new
                        {
                            Id = 33L,
                            BatteryCapacity = (short)3076,
                            BrandId = 2L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Frozen",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2572m,
                            Title = "Practical Cotton Hat"
                        },
                        new
                        {
                            Id = 34L,
                            BatteryCapacity = (short)4411,
                            BrandId = 3L,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            DisplayType = "Steel",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2838m,
                            Title = "Awesome Concrete Chicken"
                        },
                        new
                        {
                            Id = 35L,
                            BatteryCapacity = (short)5244,
                            BrandId = 3L,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            DisplayType = "Rubber",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1001m,
                            Title = "Rustic Frozen Table"
                        },
                        new
                        {
                            Id = 36L,
                            BatteryCapacity = (short)3523,
                            BrandId = 2L,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            DisplayType = "Fresh",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4093m,
                            Title = "Tasty Metal Chicken"
                        },
                        new
                        {
                            Id = 37L,
                            BatteryCapacity = (short)5371,
                            BrandId = 3L,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            DisplayType = "Fresh",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3975m,
                            Title = "Generic Soft Gloves"
                        },
                        new
                        {
                            Id = 38L,
                            BatteryCapacity = (short)3448,
                            BrandId = 1L,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            DisplayType = "Concrete",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1466m,
                            Title = "Licensed Cotton Mouse"
                        },
                        new
                        {
                            Id = 39L,
                            BatteryCapacity = (short)5457,
                            BrandId = 3L,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            DisplayType = "Wooden",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2905m,
                            Title = "Fantastic Fresh Fish"
                        },
                        new
                        {
                            Id = 40L,
                            BatteryCapacity = (short)3421,
                            BrandId = 2L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Soft",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1046m,
                            Title = "Small Plastic Pizza"
                        },
                        new
                        {
                            Id = 41L,
                            BatteryCapacity = (short)4162,
                            BrandId = 3L,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            DisplayType = "Frozen",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2671m,
                            Title = "Practical Soft Bacon"
                        },
                        new
                        {
                            Id = 42L,
                            BatteryCapacity = (short)5745,
                            BrandId = 2L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Wooden",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2207m,
                            Title = "Tasty Rubber Gloves"
                        },
                        new
                        {
                            Id = 43L,
                            BatteryCapacity = (short)4935,
                            BrandId = 3L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Plastic",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2693m,
                            Title = "Awesome Steel Mouse"
                        },
                        new
                        {
                            Id = 44L,
                            BatteryCapacity = (short)5333,
                            BrandId = 1L,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            DisplayType = "Frozen",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1947m,
                            Title = "Rustic Frozen Cheese"
                        },
                        new
                        {
                            Id = 45L,
                            BatteryCapacity = (short)4127,
                            BrandId = 3L,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            DisplayType = "Fresh",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4786m,
                            Title = "Sleek Rubber Shirt"
                        },
                        new
                        {
                            Id = 46L,
                            BatteryCapacity = (short)4175,
                            BrandId = 1L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Rubber",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3502m,
                            Title = "Incredible Plastic Computer"
                        },
                        new
                        {
                            Id = 47L,
                            BatteryCapacity = (short)3936,
                            BrandId = 1L,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            DisplayType = "Concrete",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1946m,
                            Title = "Handmade Steel Towels"
                        },
                        new
                        {
                            Id = 48L,
                            BatteryCapacity = (short)4066,
                            BrandId = 3L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Metal",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2897m,
                            Title = "Ergonomic Cotton Sausages"
                        },
                        new
                        {
                            Id = 49L,
                            BatteryCapacity = (short)4512,
                            BrandId = 3L,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            DisplayType = "Soft",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3179m,
                            Title = "Licensed Concrete Bacon"
                        },
                        new
                        {
                            Id = 50L,
                            BatteryCapacity = (short)4965,
                            BrandId = 2L,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            DisplayType = "Rubber",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4325m,
                            Title = "Handcrafted Metal Shirt"
                        },
                        new
                        {
                            Id = 51L,
                            BatteryCapacity = (short)5092,
                            BrandId = 3L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Cotton",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1813m,
                            Title = "Fantastic Rubber Table"
                        },
                        new
                        {
                            Id = 52L,
                            BatteryCapacity = (short)5242,
                            BrandId = 3L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Rubber",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1011m,
                            Title = "Refined Wooden Chair"
                        },
                        new
                        {
                            Id = 53L,
                            BatteryCapacity = (short)3368,
                            BrandId = 1L,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            DisplayType = "Metal",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3069m,
                            Title = "Small Wooden Bike"
                        },
                        new
                        {
                            Id = 54L,
                            BatteryCapacity = (short)4191,
                            BrandId = 2L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Soft",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4379m,
                            Title = "Fantastic Soft Car"
                        },
                        new
                        {
                            Id = 55L,
                            BatteryCapacity = (short)4431,
                            BrandId = 2L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Frozen",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3046m,
                            Title = "Tasty Granite Sausages"
                        },
                        new
                        {
                            Id = 56L,
                            BatteryCapacity = (short)4625,
                            BrandId = 1L,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1831m,
                            Title = "Tasty Cotton Car"
                        },
                        new
                        {
                            Id = 57L,
                            BatteryCapacity = (short)4073,
                            BrandId = 3L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Frozen",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3661m,
                            Title = "Incredible Concrete Chips"
                        },
                        new
                        {
                            Id = 58L,
                            BatteryCapacity = (short)5509,
                            BrandId = 3L,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            DisplayType = "Fresh",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4543m,
                            Title = "Unbranded Concrete Gloves"
                        },
                        new
                        {
                            Id = 59L,
                            BatteryCapacity = (short)3128,
                            BrandId = 3L,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            DisplayType = "Wooden",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4281m,
                            Title = "Rustic Steel Keyboard"
                        },
                        new
                        {
                            Id = 60L,
                            BatteryCapacity = (short)5135,
                            BrandId = 3L,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            DisplayType = "Rubber",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2512m,
                            Title = "Licensed Plastic Tuna"
                        },
                        new
                        {
                            Id = 61L,
                            BatteryCapacity = (short)4606,
                            BrandId = 2L,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            DisplayType = "Soft",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2989m,
                            Title = "Awesome Wooden Gloves"
                        },
                        new
                        {
                            Id = 62L,
                            BatteryCapacity = (short)5570,
                            BrandId = 3L,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            DisplayType = "Metal",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2941m,
                            Title = "Tasty Metal Keyboard"
                        },
                        new
                        {
                            Id = 63L,
                            BatteryCapacity = (short)5212,
                            BrandId = 2L,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            DisplayType = "Cotton",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3409m,
                            Title = "Ergonomic Rubber Salad"
                        },
                        new
                        {
                            Id = 64L,
                            BatteryCapacity = (short)5935,
                            BrandId = 3L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Concrete",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2688m,
                            Title = "Unbranded Metal Tuna"
                        },
                        new
                        {
                            Id = 65L,
                            BatteryCapacity = (short)3609,
                            BrandId = 3L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4238m,
                            Title = "Small Cotton Mouse"
                        },
                        new
                        {
                            Id = 66L,
                            BatteryCapacity = (short)5027,
                            BrandId = 1L,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3413m,
                            Title = "Intelligent Rubber Pants"
                        },
                        new
                        {
                            Id = 67L,
                            BatteryCapacity = (short)3141,
                            BrandId = 1L,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            DisplayType = "Metal",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4512m,
                            Title = "Incredible Cotton Table"
                        },
                        new
                        {
                            Id = 68L,
                            BatteryCapacity = (short)3148,
                            BrandId = 2L,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            DisplayType = "Steel",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4660m,
                            Title = "Incredible Plastic Pants"
                        },
                        new
                        {
                            Id = 69L,
                            BatteryCapacity = (short)4359,
                            BrandId = 2L,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            DisplayType = "Frozen",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2542m,
                            Title = "Small Cotton Bacon"
                        },
                        new
                        {
                            Id = 70L,
                            BatteryCapacity = (short)5149,
                            BrandId = 3L,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2444m,
                            Title = "Generic Granite Pants"
                        },
                        new
                        {
                            Id = 71L,
                            BatteryCapacity = (short)4306,
                            BrandId = 2L,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1557m,
                            Title = "Refined Steel Shoes"
                        },
                        new
                        {
                            Id = 72L,
                            BatteryCapacity = (short)3108,
                            BrandId = 2L,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            DisplayType = "Fresh",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1784m,
                            Title = "Incredible Metal Fish"
                        },
                        new
                        {
                            Id = 73L,
                            BatteryCapacity = (short)3347,
                            BrandId = 3L,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            DisplayType = "Soft",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1319m,
                            Title = "Rustic Concrete Ball"
                        },
                        new
                        {
                            Id = 74L,
                            BatteryCapacity = (short)4456,
                            BrandId = 3L,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            DisplayType = "Plastic",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4125m,
                            Title = "Incredible Fresh Soap"
                        },
                        new
                        {
                            Id = 75L,
                            BatteryCapacity = (short)3960,
                            BrandId = 3L,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            DisplayType = "Steel",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2736m,
                            Title = "Unbranded Steel Pizza"
                        },
                        new
                        {
                            Id = 76L,
                            BatteryCapacity = (short)4177,
                            BrandId = 1L,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            DisplayType = "Plastic",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1246m,
                            Title = "Small Rubber Shirt"
                        },
                        new
                        {
                            Id = 77L,
                            BatteryCapacity = (short)4111,
                            BrandId = 1L,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            DisplayType = "Cotton",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4955m,
                            Title = "Handmade Concrete Ball"
                        },
                        new
                        {
                            Id = 78L,
                            BatteryCapacity = (short)3114,
                            BrandId = 2L,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            DisplayType = "Steel",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4522m,
                            Title = "Generic Steel Gloves"
                        },
                        new
                        {
                            Id = 79L,
                            BatteryCapacity = (short)3187,
                            BrandId = 4L,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            DisplayType = "Plastic",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3203m,
                            Title = "Sleek Concrete Salad"
                        },
                        new
                        {
                            Id = 80L,
                            BatteryCapacity = (short)5926,
                            BrandId = 4L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Cotton",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1382m,
                            Title = "Handcrafted Cotton Table"
                        },
                        new
                        {
                            Id = 81L,
                            BatteryCapacity = (short)4950,
                            BrandId = 4L,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            DisplayType = "Concrete",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1898m,
                            Title = "Incredible Metal Car"
                        },
                        new
                        {
                            Id = 82L,
                            BatteryCapacity = (short)3968,
                            BrandId = 3L,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1575m,
                            Title = "Tasty Metal Chicken"
                        },
                        new
                        {
                            Id = 83L,
                            BatteryCapacity = (short)3336,
                            BrandId = 3L,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4622m,
                            Title = "Small Granite Chips"
                        },
                        new
                        {
                            Id = 84L,
                            BatteryCapacity = (short)5845,
                            BrandId = 3L,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            DisplayType = "Rubber",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3667m,
                            Title = "Refined Wooden Shoes"
                        },
                        new
                        {
                            Id = 85L,
                            BatteryCapacity = (short)5091,
                            BrandId = 2L,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            DisplayType = "Fresh",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1490m,
                            Title = "Incredible Metal Table"
                        },
                        new
                        {
                            Id = 86L,
                            BatteryCapacity = (short)3780,
                            BrandId = 3L,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            DisplayType = "Metal",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3704m,
                            Title = "Handcrafted Fresh Gloves"
                        },
                        new
                        {
                            Id = 87L,
                            BatteryCapacity = (short)5355,
                            BrandId = 1L,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            DisplayType = "Cotton",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1702m,
                            Title = "Ergonomic Concrete Salad"
                        },
                        new
                        {
                            Id = 88L,
                            BatteryCapacity = (short)3544,
                            BrandId = 2L,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            DisplayType = "Fresh",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3068m,
                            Title = "Small Granite Shirt"
                        },
                        new
                        {
                            Id = 89L,
                            BatteryCapacity = (short)4911,
                            BrandId = 1L,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            DisplayType = "Metal",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1604m,
                            Title = "Unbranded Metal Gloves"
                        },
                        new
                        {
                            Id = 90L,
                            BatteryCapacity = (short)5119,
                            BrandId = 4L,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            DisplayType = "Cotton",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2825m,
                            Title = "Incredible Concrete Sausages"
                        },
                        new
                        {
                            Id = 91L,
                            BatteryCapacity = (short)5717,
                            BrandId = 3L,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            DisplayType = "Soft",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4824m,
                            Title = "Licensed Plastic Bike"
                        },
                        new
                        {
                            Id = 92L,
                            BatteryCapacity = (short)4715,
                            BrandId = 4L,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            DisplayType = "Soft",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4454m,
                            Title = "Unbranded Rubber Gloves"
                        },
                        new
                        {
                            Id = 93L,
                            BatteryCapacity = (short)5267,
                            BrandId = 1L,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1920m,
                            Title = "Awesome Cotton Fish"
                        },
                        new
                        {
                            Id = 94L,
                            BatteryCapacity = (short)5406,
                            BrandId = 2L,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            DisplayType = "Fresh",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2497m,
                            Title = "Practical Fresh Ball"
                        },
                        new
                        {
                            Id = 95L,
                            BatteryCapacity = (short)3803,
                            BrandId = 1L,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2362m,
                            Title = "Practical Rubber Chips"
                        },
                        new
                        {
                            Id = 96L,
                            BatteryCapacity = (short)4446,
                            BrandId = 2L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Soft",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 2228m,
                            Title = "Sleek Wooden Car"
                        },
                        new
                        {
                            Id = 97L,
                            BatteryCapacity = (short)4080,
                            BrandId = 1L,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            DisplayType = "Granite",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1589m,
                            Title = "Awesome Cotton Ball"
                        },
                        new
                        {
                            Id = 98L,
                            BatteryCapacity = (short)5733,
                            BrandId = 3L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Cotton",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 1060m,
                            Title = "Unbranded Fresh Hat"
                        },
                        new
                        {
                            Id = 99L,
                            BatteryCapacity = (short)5253,
                            BrandId = 1L,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            DisplayType = "Metal",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 4705m,
                            Title = "Fantastic Fresh Ball"
                        },
                        new
                        {
                            Id = 100L,
                            BatteryCapacity = (short)5780,
                            BrandId = 1L,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            DisplayType = "Cotton",
                            PhotoPath = "uploads/IPhone_16_pro_max.jpg",
                            Price = 3234m,
                            Title = "Handmade Granite Pants"
                        });
                });

            modelBuilder.Entity("Lesson.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int?>("UserAuthRoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("UserAuthRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ef356a2-0cc5-4021-9353-22816c73b51a"),
                            Email = "admin@admin.admin",
                            Password = "admin",
                            UserAuthRoleId = 1
                        },
                        new
                        {
                            Id = new Guid("5ed5a93e-2e3e-4b4c-b025-c332c5ed7984"),
                            Age = 42,
                            BrandId = 1L,
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("7959adf8-e222-4da9-a76e-7414556da9e6"),
                            Age = 32,
                            BrandId = 1L,
                            Name = "Doe"
                        },
                        new
                        {
                            Id = new Guid("78502abe-c874-46eb-9249-bf4728999b9b"),
                            Age = 19,
                            BrandId = 1L,
                            Name = "Harry"
                        },
                        new
                        {
                            Id = new Guid("d1e16323-93ca-4e57-92a6-8efb54d73506"),
                            Age = 45,
                            BrandId = 1L,
                            Name = "Sam"
                        },
                        new
                        {
                            Id = new Guid("78aba810-053b-42ea-afac-01258adb4bf4"),
                            Age = 54,
                            BrandId = 2L,
                            Name = "John"
                        });
                });

            modelBuilder.Entity("Lesson.Models.UserAuthRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserAuthRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("Lesson.Models.Order", b =>
                {
                    b.HasOne("Lesson.Models.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("Lesson.Models.Phone", b =>
                {
                    b.HasOne("Lesson.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Lesson.Models.User", b =>
                {
                    b.HasOne("Lesson.Models.Brand", "Brand")
                        .WithMany("Users")
                        .HasForeignKey("BrandId");

                    b.HasOne("Lesson.Models.UserAuthRole", "UserAuthRole")
                        .WithMany("UsersAuth")
                        .HasForeignKey("UserAuthRoleId");

                    b.Navigation("Brand");

                    b.Navigation("UserAuthRole");
                });

            modelBuilder.Entity("Lesson.Models.Brand", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Lesson.Models.UserAuthRole", b =>
                {
                    b.Navigation("UsersAuth");
                });
#pragma warning restore 612, 618
        }
    }
}
